INSERT INTO c_percepciones_sat (id,clave,nombre) VALUES
('', '001',	UPPER('Sueldos, Salarios  Rayas y Jornales')),
('', '002',	UPPER('Gratificación Anual (Aguinaldo)')),
('', '003',	UPPER('Participación de los Trabajadores en las Utilidades PTU')),
('', '004',	UPPER('Reembolso de Gastos Médicos Dentales y Hospitalarios')),
('', '005',	UPPER('Fondo de Ahorro')),
('', '006',	UPPER('Caja de ahorro')),
('', '009',	UPPER('Contribuciones a Cargo del Trabajador Pagadas por el Patrón')),
('', '010',	UPPER('Premios por puntualidad')),
('', '011',	UPPER('Prima de Seguro de vida')),
('', '012',	UPPER('Seguro de Gastos Médicos Mayores')),
('', '013',	UPPER('Cuotas Sindicales Pagadas por el Patrón')),
('', '014',	UPPER('Subsidios por incapacidad')),
('', '015',	UPPER('Becas para trabajadores y/o hijos')),
('', '019',	UPPER('Horas extra')),
('', '020',	UPPER('Prima dominical')),
('', '021',	UPPER('Prima vacacional')),
('', '022',	UPPER('Prima por antigüedad')),
('', '023',	UPPER('Pagos por separación')),
('', '024',	UPPER('Seguro de retiro')),
('', '025',	UPPER('Indemnizaciones')),
('', '026',	UPPER('Reembolso por funeral')),
('', '027',	UPPER('Cuotas de seguridad social pagadas por el patrón')),
('', '028',	UPPER('Comisiones')),
('', '029',	UPPER('Vales de despensa')),
('', '030',	UPPER('Vales de restaurante')),
('', '031',	UPPER('Vales de gasolina')),
('', '032',	UPPER('Vales de ropa')),
('', '033',	UPPER('Ayuda para renta')),
('', '034',	UPPER('Ayuda para artículos escolares')),
('', '035',	UPPER('Ayuda para anteojos')),
('', '036',	UPPER('Ayuda para transporte')),
('', '037',	UPPER('Ayuda para gastos de funeral')),
('', '038',	UPPER('Otros ingresos por salarios')),
('', '039',	UPPER('Jubilaciones, pensiones o haberes de retiro')),
('', '044',	UPPER('Jubilaciones, pensiones o haberes de retiro en parcialidades')),
('', '045',	UPPER('Ingresos en acciones o títulos valor que representan bienes')),
('', '046',	UPPER('Ingresos asimilados a salarios')),
('', '047',	UPPER('Alimentación')),
('', '048',	UPPER('Habitación')),
('', '049',	UPPER('Premios por asistencia')),
('', '050',	UPPER('Viáticos')),
('', '051',	UPPER('Pagos por gratificaciones, primas, compensaciones, recompensas u otros a extrabajadores derivados de jubilación en parcialidades')),
('', '052',	UPPER('Pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de resoluciones judicial o de un laudo')),
('', '053',	UPPER('Pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de resoluciones judicial o de un laudo'));
